services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  sqlite-admin:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=articles.db
    restart: unless-stopped

